### ISSUE TITLE
Cannot install due to futures issue

### ISSUE THREAD

**Issue by dalemyers** [Azure/azure-cosmosdb-python#24]
This is a duplicate of: https://github.com/Azure/azure-sdk-for-python/issues/2559

The root issue is with this dependency. Nothing seems to have changed lately, either in this, or in the futures package.

**Comment by stevekludt** [comment]
I am having the same issue.  Looks like an attempt at fixing this is in PR #23.

`
Collecting futures (from azure-cosmosdb-table)
  Downloading https://files.pythonhosted.org/packages/4a/f4/418e844d868e34638486732417fb82b05031910059d88b86aaea9c70f699/futures-3.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    This backport is meant only for Python 2.
    It does not work on Python 3, and Python 3 users do not need it as the concurrent.futures package is available in the standard library.
    For projects that work on both Python 2 and 3, the dependency needs to be conditional on the Python version, like so:
    extras_require={':python_version == "2.7"': ['futures']}
`

**Comment by aarondwest** [comment]
Also running into this issue. Temporarily fixed it by building the package with this PR change and uploading it to the same location as our private Python packages: https://github.com/Azure/azure-cosmosdb-python/pull/23

**Comment by skorski** [comment]
+1

**Comment by wijkjh** [comment]
Also ran into the same issue. Solved the problem by installing futures==3.1.1 first.

On https://pypi.org/project/futures it states that the setup.py must add a conditional require on the futures package.

**Comment by dalemyers** [comment]
That works if it's feasible. However, if you use Python 3 or you have a requirements file that you give pip, you can't use that solution unfortunately.

**Comment by justinask7** [comment]
+1

**Comment by dalemyers** [comment]
This was resolved with: https://github.com/Azure/azure-cosmosdb-python/pull/23

**Comment by alfpark** [comment]
This issue isn't fully resolved until an updated package is released on [pypi](https://pypi.org/project/azure-cosmosdb-table/).

@ausfeldt is there a timeline for an updated version?
